######################################################################
# conan-demoToolchain.yml
#
# Copyright © 2025 David L. Armstrong
#
# This workflow calls the conan-multiPlatformToolchain.yml workflow
# for our demo toolchain.
#
# For more information see:
# - https://github.com/DaverSomethingSomethingOrg/conan-github-workflows
#

name: Demo Phased Toolchain build

on:
  workflow_dispatch:
    inputs:
      runner_selection-aarch64:
        type: string
        default: linux-aarch64
      runner_selection-x86_64:
        type: string
        default: linux-x86_64
      conan_recipe_remote:
        type: string
        default: "./conan-center-index"  # We provide this as a git submodule since we use a non-default branch
      toolchain_prefix:
        type: string
        default: "/opt/toolchain"
      ubuntu-aarch64-enabled:
        type: boolean
        default: false
      ubuntu-x86_64-enabled:
        type: boolean
        default: false
      almalinux-aarch64-enabled:
        type: boolean
        default: false
      almalinux-x86_64-enabled:
        type: boolean
        default: false

jobs:
  toolchain_phase1:
    uses: DaverSomethingSomethingOrg/conan-github-workflows/.github/workflows/conan-multiPlatformToolchain.yml@main
    secrets: inherit
    with:
      component_subdirectory: "components/phase1"
      save_cache_prefix: "toolchain_phase1-${{ github.run_id }}"
      runner_selection-aarch64: ${{ inputs.runner_selection-aarch64 }}
      runner_selection-x86_64: ${{ inputs.runner_selection-x86_64 }}
      conan_recipe_remote: ${{ inputs.conan_recipe_remote }}
      toolchain_prefix: ${{ inputs.toolchain_prefix }}
      ubuntu-aarch64-enabled: "${{ inputs.ubuntu-aarch64-enabled }}"
      ubuntu-aarch64-image: "nexus.homelab/conan-bootstrap-ubuntu:latest"
      ubuntu-x86_64-enabled: ${{ inputs.ubuntu-x86_64-enabled }}
      ubuntu-x86_64-image: "nexus.homelab/conan-bootstrap-ubuntu:latest"
      almalinux-aarch64-enabled: "${{ inputs.almalinux-aarch64-enabled }}"
      almalinux-aarch64-image: "nexus.homelab/conan-bootstrap-almalinux:aarch64-latest"
      almalinux-x86_64-enabled: ${{ inputs.almalinux-x86_64-enabled }}
      almalinux-x86_64-image: "nexus.homelab/conan-bootstrap-almalinux:x86_64-latest"

  toolchain_phase2:
    uses: DaverSomethingSomethingOrg/conan-github-workflows/.github/workflows/conan-multiPlatformToolchain.yml@main
    secrets: inherit
    needs: toolchain_phase1
    with:
      component_subdirectory: "components/phase2"
      restore_cache_prefix: "toolchain_phase1-${{ github.run_id }}"
      save_cache_prefix: "toolchain_phase2-${{ github.run_id }}"
      runner_selection-aarch64: ${{ inputs.runner_selection-aarch64 }}
      runner_selection-x86_64: ${{ inputs.runner_selection-x86_64 }}
      conan_recipe_remote: ${{ inputs.conan_recipe_remote }}
      toolchain_prefix: ${{ inputs.toolchain_prefix }}
      ubuntu-aarch64-enabled: "${{ inputs.ubuntu-aarch64-enabled }}"
      ubuntu-aarch64-image: "nexus.homelab/conan-bootstrap-ubuntu:latest"
      ubuntu-x86_64-enabled: ${{ inputs.ubuntu-x86_64-enabled }}
      ubuntu-x86_64-image: "nexus.homelab/conan-bootstrap-ubuntu:latest"
      almalinux-aarch64-enabled: "${{ inputs.almalinux-aarch64-enabled }}"
      almalinux-aarch64-image: "nexus.homelab/conan-bootstrap-almalinux:aarch64-latest"
      almalinux-x86_64-enabled: ${{ inputs.almalinux-x86_64-enabled }}
      almalinux-x86_64-image: "nexus.homelab/conan-bootstrap-almalinux:x86_64-latest"

  toolchain_phase3:
    uses: DaverSomethingSomethingOrg/conan-github-workflows/.github/workflows/conan-multiPlatformToolchain.yml@main
    secrets: inherit
    needs: toolchain_phase2
    with:
      upload_packages: true
      component_subdirectory: "components/phase3"
      restore_cache_prefix: "toolchain_phase2-${{ github.run_id }}"
      save_cache_prefix: "toolchain_phase3-${{ github.run_id }}"
      runner_selection-aarch64: ${{ inputs.runner_selection-aarch64 }}
      runner_selection-x86_64: ${{ inputs.runner_selection-x86_64 }}
      conan_recipe_remote: ${{ inputs.conan_recipe_remote }}
      toolchain_prefix: ${{ inputs.toolchain_prefix }}
      ubuntu-aarch64-enabled: "${{ inputs.ubuntu-aarch64-enabled }}"
      ubuntu-aarch64-image: "nexus.homelab/conan-base-ubuntu:latest"
      ubuntu-x86_64-enabled: ${{ inputs.ubuntu-x86_64-enabled }}
      ubuntu-x86_64-image: "nexus.homelab/conan-base-ubuntu:latest"
      almalinux-aarch64-enabled: "${{ inputs.almalinux-aarch64-enabled }}"
      almalinux-aarch64-image: "nexus.homelab/conan-base-almalinux:aarch64-latest"
      almalinux-x86_64-enabled: ${{ inputs.almalinux-x86_64-enabled }}
      almalinux-x86_64-image: "nexus.homelab/conan-base-almalinux:x86_64-latest"
