######################################################################
# conan-demoToolchain.yml
#
# Copyright © 2025 David L. Armstrong
#
# This workflow calls the conan-multiPlatformToolchain.yml workflow
# for our demo toolchain.
#
# For more information see:
# - https://github.com/DaverSomethingSomethingOrg/conan-github-workflows
#

name: Demo MultiPhase GCC Compiler Bootstrap Build
on:
  workflow_dispatch:
    inputs:
      runner_selection-aarch64:
        type: string
        default: linux-aarch64
      runner_selection-x86_64:
        type: string
        default: linux-x86_64
      conan_center_proxy:
        type: string
      conan_local_recipes:
        type: string
        default: "components/gcc-toolchain-recipes"
      conan_local_repo:
        type: string
        default: "http://nexus.homelab/repository/conan-homelab/"
      toolchain_prefix:
        type: string
        default: "/opt/toolchain"
      ubuntu-aarch64-enabled:
        type: boolean
        default: false
      ubuntu-x86_64-enabled:
        type: boolean
        default: false
      almalinux-aarch64-enabled:
        type: boolean
        default: false
      almalinux-x86_64-enabled:
        type: boolean
        default: false

jobs:
  bootstrap_container_image:
    uses: DaverSomethingSomethingOrg/conan-build-container/.github/workflows/conan-build-container.yml@main
    secrets: inherit
    with:
      enable_build_images: false
      container_push: true
      almalinux-aarch64-enabled: ${{ inputs.almalinux-aarch64-enabled }}
      almalinux-x86_64-enabled: ${{ inputs.almalinux-x86_64-enabled }}
      ubuntu-aarch64-enabled: ${{ inputs.ubuntu-aarch64-enabled }}
      ubuntu-x86_64-enabled: ${{ inputs.ubuntu-x86_64-enabled }}
      runner_selection-aarch64: ${{ inputs.runner_selection-aarch64 }}
      runner_selection-x86_64: ${{ inputs.runner_selection-x86_64 }}

  toolchain_phase1:
    uses: DaverSomethingSomethingOrg/conan-github-workflows/.github/workflows/conan-multiPlatformToolchain.yml@main
    secrets: inherit
    with:
      component_subdirectory: "components/phase1"
      save_cache_prefix: "toolchain_phase1-${{ github.run_id }}"
      runner_selection-aarch64: ${{ inputs.runner_selection-aarch64 }}
      runner_selection-x86_64: ${{ inputs.runner_selection-x86_64 }}
      conan_center_proxy: ${{ inputs.conan_center_proxy }}
      conan_local_repo: ${{ inputs.conan_local_repo }}
      conan_local_recipes: ${{ inputs.conan_local_recipes }}
      toolchain_prefix: ${{ inputs.toolchain_prefix }}
      ubuntu-aarch64-enabled: "${{ inputs.ubuntu-aarch64-enabled }}"
      ubuntu-aarch64-image: "nexus.homelab/conan-bootstrap-ubuntu:aarch64-latest"
      ubuntu-x86_64-enabled: ${{ inputs.ubuntu-x86_64-enabled }}
      ubuntu-x86_64-image: "nexus.homelab/conan-bootstrap-ubuntu:x86_64-latest"
      almalinux-aarch64-enabled: "${{ inputs.almalinux-aarch64-enabled }}"
      almalinux-aarch64-image: "nexus.homelab/conan-bootstrap-almalinux:aarch64-latest"
      almalinux-x86_64-enabled: ${{ inputs.almalinux-x86_64-enabled }}
      almalinux-x86_64-image: "nexus.homelab/conan-bootstrap-almalinux:x86_64-latest"

  toolchain_phase2:
    uses: DaverSomethingSomethingOrg/conan-github-workflows/.github/workflows/conan-multiPlatformToolchain.yml@main
    secrets: inherit
    needs: toolchain_phase1
    with:
      component_subdirectory: "components/phase2"
      restore_cache_prefix: "toolchain_phase1-${{ github.run_id }}"
      save_cache_prefix: "toolchain_phase2-${{ github.run_id }}"
      runner_selection-aarch64: ${{ inputs.runner_selection-aarch64 }}
      runner_selection-x86_64: ${{ inputs.runner_selection-x86_64 }}
      conan_center_proxy: ${{ inputs.conan_center_proxy }}
      conan_local_repo: ${{ inputs.conan_local_repo }}
      conan_local_recipes: ${{ inputs.conan_local_recipes }}
      toolchain_prefix: ${{ inputs.toolchain_prefix }}
      ubuntu-aarch64-enabled: "${{ inputs.ubuntu-aarch64-enabled }}"
      ubuntu-aarch64-image: "nexus.homelab/conan-bootstrap-ubuntu:aarch64-latest"
      ubuntu-x86_64-enabled: ${{ inputs.ubuntu-x86_64-enabled }}
      ubuntu-x86_64-image: "nexus.homelab/conan-bootstrap-ubuntu:x86_64-latest"
      almalinux-aarch64-enabled: "${{ inputs.almalinux-aarch64-enabled }}"
      almalinux-aarch64-image: "nexus.homelab/conan-bootstrap-almalinux:aarch64-latest"
      almalinux-x86_64-enabled: ${{ inputs.almalinux-x86_64-enabled }}
      almalinux-x86_64-image: "nexus.homelab/conan-bootstrap-almalinux:x86_64-latest"

  toolchain_phase3:
    uses: DaverSomethingSomethingOrg/conan-github-workflows/.github/workflows/conan-multiPlatformToolchain.yml@main
    secrets: inherit
    needs: toolchain_phase2
    with:
      upload_packages: true
      component_subdirectory: "components/phase3"
      restore_cache_prefix: "toolchain_phase2-${{ github.run_id }}"
      save_cache_prefix: "toolchain_phase3-${{ github.run_id }}"
      runner_selection-aarch64: ${{ inputs.runner_selection-aarch64 }}
      runner_selection-x86_64: ${{ inputs.runner_selection-x86_64 }}
      conan_center_proxy: ${{ inputs.conan_center_proxy }}
      conan_local_repo: ${{ inputs.conan_local_repo }}
      conan_local_recipes: ${{ inputs.conan_local_recipes }}
      toolchain_prefix: ${{ inputs.toolchain_prefix }}
      ubuntu-aarch64-enabled: "${{ inputs.ubuntu-aarch64-enabled }}"
      ubuntu-aarch64-image: "nexus.homelab/conan-base-ubuntu:aarch64-latest"
      ubuntu-x86_64-enabled: ${{ inputs.ubuntu-x86_64-enabled }}
      ubuntu-x86_64-image: "nexus.homelab/conan-base-ubuntu:x86_64-latest"
      almalinux-aarch64-enabled: "${{ inputs.almalinux-aarch64-enabled }}"
      almalinux-aarch64-image: "nexus.homelab/conan-base-almalinux:aarch64-latest"
      almalinux-x86_64-enabled: ${{ inputs.almalinux-x86_64-enabled }}
      almalinux-x86_64-image: "nexus.homelab/conan-base-almalinux:x86_64-latest"

  build_container_image:
    uses: DaverSomethingSomethingOrg/conan-build-container/.github/workflows/conan-build-container.yml@main
    secrets: inherit
    with:
      enable_build_images: true
      container_push: true
      almalinux-aarch64-enabled: ${{ inputs.almalinux-aarch64-enabled }}
      almalinux-x86_64-enabled: ${{ inputs.almalinux-x86_64-enabled }}
      ubuntu-aarch64-enabled: ${{ inputs.ubuntu-aarch64-enabled }}
      ubuntu-x86_64-enabled: ${{ inputs.ubuntu-x86_64-enabled }}
      runner_selection-aarch64: ${{ inputs.runner_selection-aarch64 }}
      runner_selection-x86_64: ${{ inputs.runner_selection-x86_64 }}